language: java
sudo: required
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean install -Pqulice --errors --batch-mode --quiet
  - mvn clean --quiet
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
after_success:
  - mvn verify --quiet --batch-mode -Pcoverage -Pqulice
  - "bash <(curl -s https://codecov.io/bash)"
